### ISSUE TITLE
GPU implementation 

### ISSUE THREAD

**Issue by adhikarirsr** [lucfra/LDS-GNN#10]
This is such an interesting idea and nicely done work. Thanks a lot!

Is there a GPU implementation of your algorithm? I was testing digits example and it takes a lot of time.

**Comment by lucfra** [comment]
HI @adhikarirsr , 

Sorry for the late reply and thanks for your interest in our work!

If I remember well, the code should run on the GPU if it is available. Probably it's slow because the runtime scales quadratically in the number of training points. 
A way to go around this could be to implement a stochastic version of the algorithm, but this is not in our plans at the moment.  See also this https://github.com/lucfra/LDS-GNN/issues/6 

Hope this helps,  and let me know if there are any other issues.

Cheers 
Luca

**Comment by adhikarirsr** [comment]
Hi @lucfra ,

I figured out that it is GPU compatible. That's why closed the issue. I had to install tf 1.15 but while doing so I installed CPU version of the tf. That's why I was having the issue. I was just being a fool. I have a few more questions that are not issues. Is it fine if I email you @ igor_mio@hotmail.it ?

Thanks for the reply.

**Comment by lucfra** [comment]
Sure, please go ahead (I'm a bit busy these days but will try to reply soon!)

**Comment by adhikarirsr** [comment]
Did you get my email?
