### ISSUE TITLE
The implementation of the baseline method kNN-GCN?

### ISSUE THREAD

**Issue by hugochan** [lucfra/LDS-GNN#3]
Hi,

Thank you for sharing the code of this awesome work!
I have one question about the kNN-GCN baseline method mentioned in the paper. Since the kNN graph is directed, I was wondering what is your strategy to apply GCNs to the directed kNN-graph. Specifically, how did you normalize the non-symmetric adjacency matrix?

Thanks!

**Comment by lucfra** [comment]
Hi @hugochan, 

thanks for your message and interest in our work!

For the baseline we tried using both mutual KNN graph (symmetric) and also simply the non-symmetric graph. For the datasets we used, we saw that there was very little difference and reported in the paper results for non-symmetric one. 

When KNN-graph is used as initialization for LDS, we instead only used the upper triangular part. This has been done to keep the implementation as simple as possible. Anyway, since KNN-graph  provides only an initialization, I wouldn't expect major differences with a different strategy. 

Cheers, 
Luca
